### ISSUE TITLE
implement data module for hf2

### ISSUE THREAD

**Issue by changhoonhahn** [galactic-ai/haloflow#5]
implement data module for hf2 simulations. This will provide the training/testing data for NPE training.

**Comment by changhoonhahn** [comment]
Implemented preliminary data module for hf2 in [82ca572](https://github.com/galactic-ai/haloflow/commit/82ca5727448d3a9639e7b2cd80ac4408955e6ee9). 

`data.hf2_centrals` outputs training or test data set of central subhalos for a given simulation. Below is a demo of the SHMR and color-color relation. 
![Image](https://github.com/user-attachments/assets/921d16de-c835-4961-82d0-2ea6a1ff3d60)
![Image](https://github.com/user-attachments/assets/3bfdc863-0813-40c4-bb5d-84b1e1ac60a9)

Interestingly, but unsurprisingly, the color color predictions are dramatically different among the different simulations.

Currently, `data.hf2_centrals` only supports magnitudes and morphologies. 
- [ ] implement satellite luminosity and richness

**Comment by changhoonhahn** [comment]
Hm, I ran into a strange discrepancy. I previously took stellar mass and halo mass from `HaloFlow_{simulation}_Subhalos.csv` and the rest of the data from `HaloFlow_{simulation}.csv`. This was because I didn't realize `HaloFlow_{simulation}.csv` also has `SubhaloMassType_stars` and `SubhaloMassType_dm`. 

After your comments in #8, I realized I should probably be using the masses from `HaloFlow_{simulation}.csv` so I updated the data module in [cd99906](https://github.com/galactic-ai/haloflow/commit/cd99906e9d3ad083762cfea5f6bebdc99c12b55e). To my surprise, it actually changed the SHMR: 
![image](https://github.com/user-attachments/assets/b4ac1dd1-9261-4d43-8d41-afd8b091addb)
The SHMR is now significantly tighter. 

@cbottrell could you confirm that `SubhaloMassType_stars` and `SubhaloMassType_dm` in `HaloFlow_{simulation}.csv` is what I should be using? Do you happen to know why there's a discrepancy?

**Comment by cbottrell** [comment]
@changhoonhahn, for the resolution calibrations and all plots, I've been using the `Group_M_Crit200` as halo mass and `SubhaloMassType_stars` as stellar mass. You can find these in log units assuming h=0.6774 in the `HaloFlow_{simulation}.csv` tables. Lengths are in [pkpc]. Masses are in [Msun]. I've set things up so that you should be able to do everything from these tables. I've merged the group and subhalo data and morphologies for each galaxy, in each band, for all camera angles into those tables.

The `HaloFlow_{simulation}_Subhalos.csv` tables are all in code units taken directly from the sims. You can abandon these tables. As for the discrepancy and tighter SHMR, is it because you are using Subhalo masses rather than Group masses? The scatter will be particularly tighter if you are including satellites with `SubhaloMass` -- because the `SubhaloMass` for satellites will be closer to the dynamical masses you would infer from gas kinematics, rather than the group halo masses that would be inferred from weak lensing or group dynamics. You can restrict to centrals in my catalogues with `GroupFirstSub=1`. But this increase in scatter will also hold to some extent for centrals because of the difference in how `SubhaloMass` and `Group_M_Crit200` are defined.

My understanding was that you would have used the `Group_M_Crit200` in the previous paper as well. But I could be wrong. In any case, if we decide to train with Subhalo masses, we should be using `SubhaloMass` and not `SubhaloMassType_dm`. We want the whole dynamical mass, not just the dark matter.

**Comment by changhoonhahn** [comment]
Thanks for the clarification @cbottrell. I've updated everything to use `Group_M_Crit200` for halo mass ([8fe68e2](https://github.com/galactic-ai/haloflow/commit/8fe68e20da3db96365004027a6b0e4de96f9e3e0))

Here's how the SHMR looks now: 
![image](https://github.com/user-attachments/assets/00354e9c-706d-4a4f-a3c8-5c5ff1dc4110)
